post_install() {
    # Создаем группу, если её нет
    getent group uinput >/dev/null || groupadd -r uinput

    # Пытаемся перезагрузить udev правила
    udevadm control --reload-rules && udevadm trigger

    echo "RU"
    echo "------------------------------------------------------------------------"
    echo "  PadKey Mapper установлен!"
    echo "  "
    echo "  ВАЖНО: Для работы без sudo необходимо добавить вашего пользователя"
    echo "  в группу 'uinput'. Выполните следующую команду в терминале:"
    echo "  "
    echo "    sudo usermod -aG uinput \$USER"
    echo "  "
    echo "  Затем выйдите из системы и войдите снова (или перезагрузитесь)."
    echo "------------------------------------------------------------------------"

    echo "EN"
    echo "------------------------------------------------------------------------"
    echo "  PadKey Mapper installed!"
    echo "  "
    echo "  WARNING: For correct launch without sudo you need add your user"
    echo "  to group 'uinput'. Run this command in terminal:"
    echo "  "
    echo "    sudo usermod -aG uinput \$USER"
    echo "  "
    echo "  Then logout and login to system (or reboot)."
    echo "------------------------------------------------------------------------"
}

post_upgrade() {
    post_install
}

post_remove() {
    # Опционально: удаляем правило, но группу обычно оставляют
    echo "Правила udev удалены. Группа 'uinput' осталась в системе."
    echo "udev rules are removed. Group `uinput` is still in system"
}
